### ISSUE TITLE
Deployment to ECS

### ISSUE THREAD

**Issue by dmasip-rxd** [andfanilo/streamlit-light-leaflet#1]
Hi, thanks for a very useful tool.

I'm trying to develop a streamlit app and put it in ECS, using this component. For that purpose, I've created a docker image to handle the `npm` part of the app. Basically I tried to follow your guidelines, and run `npm install` and `npm run start`. 

```
FROM mhart/alpine-node:14

COPY streamlit-light-leaflet /streamlit_light_leaflet

WORKDIR /streamlit_light_leaflet/my_component/frontend

RUN npm install

# Entrypoint will allow different executions for the same docker
CMD ["npm", "run", "start"]
```

I've created an `npm` service in my docker compose file, and this part looks like

```
    npm:
        image: npm
        build:
            context: ./docker-npm
        ports:
            - "3001:3001"
        tty: true 
```

Everything works well locally. My issue is that when moving to ECS, when trying to show the map in my app, I get the following error:

![image](https://user-images.githubusercontent.com/68583963/104913302-ae08b880-598d-11eb-9c08-4c048598a025.png)

When accessing the port 3001 in ecs, I can see the map and interact with it, but not in the map. 

I'm aware this is not very central to this repo, but if you have any clue of what's going on and what might be a solution that'd be very helpful.

Thanks!
